# Generated by Django 4.0.6 on 2022-11-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classroom', models.IntegerField()),
                ('position', models.CharField(choices=[('Dyrektor', 'Dyrektor'), ('Wicedyrektor', 'Wicedyrektor'), ('Nauczyciel', 'Nauczyciel'), ('Nauczyciel przedmiotów zawodowych', 'Nauczyciel przedmiotów zawodowych')], default='Nauczyciel', max_length=40)),
            ],
        ),
    ]
