# Generated by Django 4.0.6 on 2022-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_teacher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Dyrektor', 'Dyrektor'), ('Wicedyrektor', 'Wicedyrektor'), ('Nauczyciel', 'Nauczyciel'), ('Nauczyciel przedmiotów zawodowych', 'Nauczyciel przedmiotów zawodowych'), ('Samorząd uczniowski', 'Samorząd uczniowski'), ('Pedagog', 'Pedagog'), ('Psycholog', 'Psycholog')], default='Nauczyciel', max_length=40),
        ),
    ]
