# Generated by Django 4.0.6 on 2022-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_teacher_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='additional_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
